---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: compactor
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      targetPort: http
      protocol: TCP
      name: http
    - port: 10902
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: compactor
